scrapeConfigs:
  kubernetes-api-servers:            { enabled: false }
  kubernetes-nodes:                  { enabled: false }
  kubernetes-nodes-cadvisor:         { enabled: false }
  kubernetes-pods:                   { enabled: false }
  kubernetes-pods-slow:              { enabled: false }
  kubernetes-service-endpoints:      { enabled: false }
  kubernetes-service-endpoints-slow: { enabled: false }
  kubernetes-services:               { enabled: false }
  prometheus-pushgateway:            { enabled: false }
  blackbox-http:
    enabled: true
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://google.com
          - https://prometheus.io
          - https://expired.badssl.com
          - https://httpstat.us/500
          - https://no-such-host-xyz.invalid
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-prometheus-blackbox-exporter:9115

alertmanager:             { enabled: false }
prometheus-node-exporter: { enabled: false }
kube-state-metrics:       { enabled: false }
prometheus-pushgateway:   { enabled: false }