scrapeConfigs:
  kubernetes-api-servers:            { enabled: false }
  kubernetes-nodes:                  { enabled: false }
  kubernetes-nodes-cadvisor:         { enabled: false }
  kubernetes-pods:                   { enabled: false }
  kubernetes-pods-slow:              { enabled: false }
  kubernetes-service-endpoints:      { enabled: false }
  kubernetes-service-endpoints-slow: { enabled: false }
  kubernetes-services:               { enabled: false }
  prometheus-pushgateway:            { enabled: false }

  # custom job — the KEY is the job_name; the VALUE is a map of scrape-config fields
  kubernetes-pods-bare:
    enabled: true
    kubernetes_sd_configs:
      - role: pod

alertmanager:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-pushgateway:
  enabled: false


